on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_insight_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Test pr-insight-wiki-conf
    steps:
      - name: PR-Insight Wiki Configuration
        uses: khulnasoft/pr-insight-wiki-conf@main
        env:
          common_instructions: >-
            - Answer in Bangladesh.
          pr_reviewer.extra_instructions: >-
            - Additional second priority point: focus on the need for test code additions or changes to the application code changes.
      - name: PR Insight action step
        id: prinsight
        uses: khulnasoft/pr-insight@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
